### PR TITLE
Missing EAFs

### PR DESCRIPTION
**Pull request by VolkerGast**

### CODE REVIEW

**Comment by BobBorges** [comment]
Merging this takes longer than I thought -- I am working on it.

**Comment by BobBorges** [comment]
@VolkerGast do any of these files you pushed have extra tiers or manual corrections? I mean tiers or edits that were added after the original annotation process? It looks like you pushed all the files -- not only ones that we didn't already have -- so I'm just considering how to handle this in the best way.

**Comment by VolkerGast** [comment]
No, there were no extra tiers and I think I pushed only the files from the file you sent me. I wrote a bash script that looped through the file, checked if the file existed on my computer, and if so, copied it, else gave the file name.

What's wrong with the files?

Volker

Sent from MailDroid

-----Original Message-----

**Comment by VolkerGast** [comment]
... and I remember seing a message telling ne about ~ 15.000 files, which was the difference between your files and mine.

Volker

Sent from MailDroid

-----Original Message-----

**Comment by BobBorges** [comment]
Nothing wrong -- I'm just being careful :D

**Pull request merged**
